# Generated by Django 5.1.8 on 2025-04-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre Video')),
                ('description', models.TextField(verbose_name='Descripcion Video')),
            ],
        ),
    ]
